/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Controller.PlaceOrderController;
import Model.Product;
import java.awt.Image;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author ThinkBook
 */
public class ProductItemPanel extends javax.swing.JPanel {
    
    private Product product; 
    private PlaceOrderController placeorderController; 
    /**
     * Creates new form ProductItemPanel
     */
    public ProductItemPanel() {
        initComponents();
    }
    
    public ProductItemPanel(Product pro) {
        initComponents();
        this.product = pro;
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
        String formattedPrice = currencyFormat.format(pro.getPrice());
        pro_name.setText(pro.getName());
        pro_price.setText(formattedPrice);
        ImageIcon imgIcon = new ImageIcon(pro.getImage());
        Image img = imgIcon.getImage();

        int width = pro_img.getWidth();
        int height = pro_img.getHeight();

        if (width == 0 || height == 0) {
            width = 180;
            height = 160;
        }

        Image scaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        pro_img.setIcon(new ImageIcon(scaled));
        
        if ("Unavailable".equalsIgnoreCase(pro.getStatus()) || pro.getStock() <= 0) {
        
            items_panel.setBackground(java.awt.Color.GRAY);
            jPanel2.setBackground(java.awt.Color.GRAY);

            pro_name.setForeground(java.awt.Color.LIGHT_GRAY);
            pro_price.setForeground(java.awt.Color.LIGHT_GRAY);

            add_btn.setEnabled(false);
            add_btn.setText("OOS");
            add_btn.setBackground(java.awt.Color.DARK_GRAY);

            pro_quantity.setEnabled(false);

        } else {
            items_panel.setBackground(new java.awt.Color(255, 51, 51));
            jPanel2.setBackground(new java.awt.Color(204, 204, 204));

            add_btn.setEnabled(true);
            add_btn.setText("Add");
            add_btn.setBackground(new java.awt.Color(255, 51, 51));

            pro_quantity.setEnabled(true);
        }
    }

    
    public javax.swing.JButton getAddButton(){
        return add_btn;
    }
    
    public JPanel getitems_panel(){
        return items_panel;
    }
    
    // changes:
    public void setAdminController(PlaceOrderController controller) {
        this.placeorderController = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        items_panel = new javax.swing.JPanel();
        pro_name = new javax.swing.JLabel();
        pro_price = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pro_img = new javax.swing.JLabel();
        pro_quantity = new javax.swing.JSpinner();
        add_btn = new javax.swing.JButton();

        items_panel.setBackground(new java.awt.Color(255, 51, 51));
        items_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pro_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pro_name.setForeground(new java.awt.Color(255, 255, 255));
        pro_name.setText("Productname");

        pro_price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pro_price.setForeground(new java.awt.Color(255, 255, 255));
        pro_price.setText("100.000");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pro_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pro_img, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );

        pro_quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        add_btn.setBackground(new java.awt.Color(255, 51, 51));
        add_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout items_panelLayout = new javax.swing.GroupLayout(items_panel);
        items_panel.setLayout(items_panelLayout);
        items_panelLayout.setHorizontalGroup(
            items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(items_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addGroup(items_panelLayout.createSequentialGroup()
                        .addComponent(pro_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pro_price))
                    .addGroup(items_panelLayout.createSequentialGroup()
                        .addComponent(pro_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_btn)))
                .addContainerGap())
        );
        items_panelLayout.setVerticalGroup(
            items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(items_panelLayout.createSequentialGroup()
                .addGroup(items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pro_name)
                    .addComponent(pro_price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pro_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_btn))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(items_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(items_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        int qty = (int) pro_quantity.getValue();
        
        if (qty <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Quantity must at least 1!", 
            "Quantity error", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
        
        if (placeorderController != null && product != null) {
            placeorderController.addProductToTable(product.getId(), qty); // getID from product then pass ID , qty to admincontroller
            System.out.println("Sending: ID = " + product.getId() + ", Qty = " + qty);
        }
        
        pro_quantity.setValue(0); // reset quantity
    }//GEN-LAST:event_add_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JPanel items_panel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pro_img;
    private javax.swing.JLabel pro_name;
    private javax.swing.JLabel pro_price;
    private javax.swing.JSpinner pro_quantity;
    // End of variables declaration//GEN-END:variables
}
