/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Image;
import javax.swing.ImageIcon;
import Controller.StaffProfileController;
/**
 *
 * @author ThinkBook
 */
public class StaffProfile extends javax.swing.JPanel {

    /**
     * Creates new form StaffProfile
     */
    private StaffProfileController staff_controller = new StaffProfileController(this);
    private boolean isConfirmingUpdate = false;
    
    public StaffProfile() {
        this.setPreferredSize(null);
        initComponents();
        ImageIcon ii = new ImageIcon(getClass().getResource("/gallery/a7_brother_login_logo.png"));
        Image image = (ii).getImage().getScaledInstance(380, 380, Image.SCALE_SMOOTH);
        ii = new ImageIcon(image);
        img.setIcon(ii);
        lock_panel.setVisible(true);
        password_field.addFocusListener(new java.awt.event.FocusAdapter() {
        
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (String.valueOf(password_field.getPassword()).equals("Enter new password")) {
                    password_field.setText("");
                    password_field.setForeground(java.awt.Color.BLACK);
                    password_field.setEchoChar('*');
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (password_field.getPassword().length == 0) {
                    password_field.setText("Enter new password");
                    password_field.setForeground(java.awt.Color.GRAY);
                    password_field.setEchoChar('*');
                }
            }
        });
        resetPasswordPlaceholder();
    }
    
    public void lockSystem(){
        lock_panel.setVisible(true);
        isConfirmingUpdate = false; 
        asking_label.setText("Please enter your password to continue");
        password_check.setText("");
        resetPasswordPlaceholder();
    }
    
    public void resetPasswordPlaceholder() {
        password_field.setText("Enter new password");
        password_field.setForeground(java.awt.Color.GRAY);
        password_field.setEchoChar('*');
        showpass_btn.setText("Show Password");
    }
    
    public void clearPasswordField() {
        password_field.setText("");
    }
    
    public String getEmail(){
        return email_field.getText().trim();
    }
    
    public String getUsername(){
        return username_field.getText();
    }
    
    public char[] getPassword(){ 
        char[] pass = password_field.getPassword();
    
        if (pass == null) {
            return new char[0];
        }
        String passStr = String.valueOf(pass);
        if (passStr.equals("Enter new password")) {
            return new char[0];
        }
        return pass;
    }
    
    public void setUsernameField(String username){
        username_field.setText(username);
    }
    
    public void setEmailField(String email){
        email_field.setText(email);
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lock_panel = new javax.swing.JPanel();
        asking_label = new javax.swing.JLabel();
        password_check = new javax.swing.JPasswordField();
        submit_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        password_field = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        edit_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showpass_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        img.setBackground(new java.awt.Color(255, 51, 51));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/a7_brother_login_logo.png"))); // NOI18N
        img.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(289, 289, 289)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Brother Chicken");

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Đỉnh cao ẩm thực của Việt Nam. Độc nhất và ngon nhất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(125, 125, 125))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        lock_panel.setBackground(new java.awt.Color(213, 212, 212, 252));
        lock_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lock_panel.setToolTipText("");

        asking_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        asking_label.setText("Please enter your password to continue");

        submit_btn.setBackground(new java.awt.Color(255, 51, 51));
        submit_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lock_panelLayout = new javax.swing.GroupLayout(lock_panel);
        lock_panel.setLayout(lock_panelLayout);
        lock_panelLayout.setHorizontalGroup(
            lock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lock_panelLayout.createSequentialGroup()
                .addGroup(lock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lock_panelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(lock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asking_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password_check)))
                    .addGroup(lock_panelLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(submit_btn)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        lock_panelLayout.setVerticalGroup(
            lock_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lock_panelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(asking_label)
                .addGap(27, 27, 27)
                .addComponent(password_check, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(submit_btn)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        password_field.setForeground(new java.awt.Color(204, 204, 204));
        password_field.setText("Enter new password");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        email_field.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        edit_btn.setBackground(new java.awt.Color(255, 51, 51));
        edit_btn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Username");

        username_field.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Email");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("Staff Profile");

        showpass_btn.setBackground(new java.awt.Color(255, 51, 51));
        showpass_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        showpass_btn.setForeground(new java.awt.Color(255, 255, 255));
        showpass_btn.setText("Show password");
        showpass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(372, 372, 372))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(showpass_btn)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(username_field, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(edit_btn)))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showpass_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(lock_panel, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 705, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(lock_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(778, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(lock_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        char[] inputPassword = password_check.getPassword();
        Model.User currentUser = Model.Session.getCurrentUser();

        if (currentUser != null) {
            char[] sessionPass = currentUser.getPassword();

            if (sessionPass == null) {
                sessionPass = new char[0];
            }
            
            if (java.util.Arrays.equals(inputPassword, sessionPass)) {

                if (isConfirmingUpdate) {
                    
                    boolean success = staff_controller.updateProfile();
                    
                    if (success) {
                        lock_panel.setVisible(false);
                        resetPasswordPlaceholder(); 
                        
                        updateParentWelcome();
                        
                        isConfirmingUpdate = false; 
                        asking_label.setText("Please enter your password to continue"); 
                    }
                    
                } else {
                    lock_panel.setVisible(false);
                    staff_controller.loadUserProfile(currentUser);
                }
                
                password_check.setText("");
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Wrong Password!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submit_btnActionPerformed
    
    private void updateParentWelcome() {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        if (parentWindow instanceof UI.Admistration) {
            ((UI.Admistration) parentWindow).refreshWelcomeLabel();
        }
    }
    
    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        isConfirmingUpdate = true;
        
        asking_label.setText("Enter old password to confirm changes"); 
        
        password_check.setText("");
        
        lock_panel.setVisible(true);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void showpass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass_btnActionPerformed
        // TODO add your handling code here:
        Model.User currentUser = Model.Session.getCurrentUser();
        String sessionPass = "";
        if (currentUser != null && currentUser.getPassword() != null) {
            sessionPass = new String(currentUser.getPassword());
        }

        String currentText = String.valueOf(password_field.getPassword());

        if (password_field.getEchoChar() == '*') {
        
            if (currentText.equals("Enter new password")) {
                password_field.setText(sessionPass);
                password_field.setForeground(java.awt.Color.BLACK); // Đổi màu chữ đen
            }

            password_field.setEchoChar((char) 0); 
            showpass_btn.setText("Hide Password");

        } else {
        
            password_field.setEchoChar('*'); 
            showpass_btn.setText("Show Password"); 

            if (currentText.equals(sessionPass)) {
                password_field.setText("Enter new password");
                password_field.setForeground(java.awt.Color.GRAY);
            }
        }
    }//GEN-LAST:event_showpass_btnActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asking_label;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel lock_panel;
    private javax.swing.JPasswordField password_check;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton showpass_btn;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
